openapi_url: /v1/llm/security/openapi.json
docs_url: /v1/llm/security/docs
title: Infosys Responsible AI - Security - OpenAPI 3.0
description: API specs for Infosys Responsible AI Security pillar in OpenAPI 3.0 format
terms_of_service: https://www.infosys.com
contact:
    email: Impact@infosys.com
license_info:
    name: Infosys
    url: https://www.infosys.com
version: v$version
openapi_tags:
    - name: Model Security
      description: Operations required for a Model Security 
      externalDocs:
        description: Find out more
        url: https://www.infosys.com