openapi_url: /rai/v1/models/openapi.json
docs_url: /rai/v1/models/docs
title: Infosys Responsible AI - LLM Moderation Models - OpenAPI 3.0
description: API specs for Infosys Responsible AI LLM Moderation layer Models in OpenAPI 3.0 format
termsOfService: https://www.infosys.com
contact:
  email: aina@infosys.com
license_info:
  name: Infosys
  url: https://www.infosys.com
version: 0.0.1
openapi_tags:
  - name: LLM Moderation
    description: Operations required for LLM moderation proxy.
    externalDocs:
      description: Find out more
      url: https://www.infosys.com
#http://localhost:8000/rai/v1/models/docs